### ISSUE TITLE
Poetry "add" will not work

### ISSUE THREAD

**Issue by ncataldo11** [Nuo-Chen/python-intermetiate-inflammation#2]
Poetry will not add matplotlib or numpy. When I try to add I am getting the error "Because inflammation depends on python3 (^3.8) which doesn't match any versions, version solving failed."

**Comment by ncataldo11** [comment]
@ncataldo11

**Comment by Nuo-Chen** [comment]
You can specify which version you want to add to the poetry like `poetry add matplotlib@^3.5 numpy@^1.21`

**Comment by ncataldo11** [comment]
> You can specify which version you want to add to the poetry like `poetry add matplotlib@^3.5 numpy@^1.21`

Unfortunately, this did not solve the issue. This is the full error:

Noelles-MacBook-Pro:python-intermediate-inflammation noellecataldo$ poetry add matplotlib@^3.5

Updating dependencies
Resolving dependencies... (0.1s)

Because inflammation depends on python3 (^3.8) which doesn't match any versions, version solving failed.

**Comment by Nuo-Chen** [comment]
Could you show me your `pyproject.toml` which generated by `peotry init`?
