### ISSUE TITLE
Bug Report: Embedded Icon not appearing

### ISSUE THREAD

**Issue by wilkija** [Nuo-Chen/python-intermetiate-inflammation#6]
Chrome browser using Wind 10. Icon is not loading properly. 

https://github.com/Nuo-Chen/python-intermetiate-inflammation/blob/258e120af56b7474020920e369a40205ad7b0ffb/README.md?plain=1#L2 

![image](https://user-images.githubusercontent.com/95652243/225946808-aa395b5f-184c-482b-a3be-e382d22dd424.png)

**Comment by Nuo-Chen** [comment]
This is a duplication of #3
